In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
# Load training data
X_train = pd.read_csv(
    r"D:\imu-har-exoskeleton-ai\data\UCI HAR Dataset\UCI HAR Dataset\train\X_train.txt",
    sep=r"\s+",
    header=None
)

y_train = pd.read_csv(
    r"D:\imu-har-exoskeleton-ai\data\UCI HAR Dataset\UCI HAR Dataset\train\y_train.txt",
    header=None
)

# Load testing data
X_test = pd.read_csv(
    r"D:\imu-har-exoskeleton-ai\data\UCI HAR Dataset\UCI HAR Dataset\test\X_test.txt",
    sep=r"\s+",
    header=None
)

y_test = pd.read_csv(
    r"D:\imu-har-exoskeleton-ai\data\UCI HAR Dataset\UCI HAR Dataset\test\y_test.txt",
    header=None
)

In [3]:
# Load feature names
features = pd.read_csv(
    r"D:\imu-har-exoskeleton-ai\data\UCI HAR Dataset\UCI HAR Dataset\features.txt",
    sep=r"\s+",
    header=None,
    names=["Index", "Feature"]
)

In [4]:
# Assign feature names
X_train.columns = features["Feature"]
X_test.columns = features["Feature"]

In [5]:
# Check shapes
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (7352, 561)
y_train: (7352, 1)
X_test: (2947, 561)
y_test: (2947, 1)


In [6]:
activity_labels = {
    1: "WALKING",
    2: "WALKING_UPSTAIRS",
    3: "WALKING_DOWNSTAIRS",
    4: "SITTING",
    5: "STANDING",
    6: "LAYING"
}

In [7]:
y_train["Activity"] = y_train[0].map(activity_labels)
y_test["Activity"] = y_test[0].map(activity_labels)

In [8]:
y_train.head()

,0,Activity
0,5,STANDING
1,5,STANDING
2,5,STANDING
3,5,STANDING
4,5,STANDING


In [10]:
label_encoder = LabelEncoder()

In [11]:
y_train_encoded = label_encoder.fit_transform(y_train["Activity"])
y_test_encoded = label_encoder.transform(y_test["Activity"])

In [12]:
print(y_train_encoded[:10])

[2 2 2 2 2 2 2 2 2 2]


In [13]:
print(label_encoder.classes_)

['LAYING' 'SITTING' 'STANDING' 'WALKING' 'WALKING_DOWNSTAIRS'
 'WALKING_UPSTAIRS']


In [14]:
for i, label in enumerate(label_encoder.classes_):
    print(i, "->", label)

0 -> LAYING
1 -> SITTING
2 -> STANDING
3 -> WALKING
4 -> WALKING_DOWNSTAIRS
5 -> WALKING_UPSTAIRS


In [17]:
X_train_final, X_val, y_train_final, y_val = train_test_split(
    X_train,
    y_train_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_train_encoded
)

In [18]:
print("X_train_final:", X_train_final.shape)
print("X_val:", X_val.shape)

print("y_train_final:", y_train_final.shape)
print("y_val:", y_val.shape)

X_train_final: (5881, 561)
X_val: (1471, 561)
y_train_final: (5881,)
y_val: (1471,)


In [19]:
print("Final Training Set:", X_train_final.shape)
print("Validation Set:", X_val.shape)
print("Test Set:", X_test.shape)

Final Training Set: (5881, 561)
Validation Set: (1471, 561)
Test Set: (2947, 561)


In [ ]:
# ML-ready datasets prepared
print(np.unique(y_train_final))
print(np.unique(y_val))
print(np.unique(y_test_encoded))

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
